#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("ImmersiveModeSample.Resource", IsApplication=true)]

namespace ImmersiveModeSample
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f050005
			public const int horizontal_page_margin = 2131034117;
			
			// aapt resource value: 0x7f050004
			public const int margin_huge = 2131034116;
			
			// aapt resource value: 0x7f050003
			public const int margin_large = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int margin_medium = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int margin_small = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int margin_tiny = 2131034112;
			
			// aapt resource value: 0x7f050006
			public const int vertical_page_margin = 2131034118;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_launcher = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int tile = 2130837506;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080005
			public const int action_about = 2131230725;
			
			// aapt resource value: 0x7f080002
			public const int action_fullscreen = 2131230722;
			
			// aapt resource value: 0x7f080003
			public const int action_immersive = 2131230723;
			
			// aapt resource value: 0x7f080004
			public const int action_immersive_stick = 2131230724;
			
			// aapt resource value: 0x7f080000
			public const int sample_main_layout = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int sample_output = 2131230721;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f070000
			public const int main = 2131165184;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040004
			public const int helloworld = 2130968580;
			
			// aapt resource value: 0x7f040002
			public const int intro_message = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int sample_action = 2130968579;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060001
			public const int AppTheme = 2131099649;
			
			// aapt resource value: 0x7f060006
			public const int Log = 2131099654;
			
			// aapt resource value: 0x7f060000
			public const int Theme_Base = 2131099648;
			
			// aapt resource value: 0x7f060002
			public const int Widget = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int Widget_SampleMessage = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int Widget_SampleMessageTile = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int Widget_SampleOutput = 2131099653;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
