// This file has been autogenerated from parsing an Objective-C header file added in Xcode.
using System;
using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace StoryboardDemo {

	public partial class CategoryTableViewController : UITableViewController {
		
		public CategoryTableViewController(IntPtr handle) : base (handle) {
		}
		
		public override void ViewDidLoad() {
			var source = new CategoryTableViewSource();
			source.LoadDataAsync(() => InvokeOnMainThread(() => this.TableView.ReloadData()));
			this.TableView.Source = source;
		}
		
		public override void PrepareForSegue(UIStoryboardSegue segue, NSObject sender) {
			var dest = segue.DestinationViewController as ProductTableViewController;
			var source = this.TableView.Source as CategoryTableViewSource;
			var selected = this.TableView.IndexPathForSelectedRow;
			var category = source.Data[selected.Row];
			dest.CategoryId = category.CategoryId;
			dest.CategoryName = category.CategoryName;
		}
	}
}
