// This file has been autogenerated from parsing an Objective-C header file added in Xcode.
using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace StoryboardDemo {

	public partial class ProductDetailViewController : UITableViewController {
		
		public long ProductId {
			get;
			set;
		}
		
		public string ProductName {
			get;
			set;
		}
		
		public ProductDetailViewController(IntPtr handle) : base (handle) {
		}
		
		public override void ViewDidLoad() {
			this.NavigationItem.Title = this.ProductName;
			var source = new ProductDetailTableViewSource();
			this.TableView.Source = source;
		}
	}
}
