// This file has been autogenerated from parsing an Objective-C header file added in Xcode.
using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace StoryboardDemo {

	public partial class ProductTableViewController : UITableViewController {
		
		public string CategoryName {
			get;
			set;
		}
		
		public long CategoryId {
			get;
			set;
		}
		
		public ProductTableViewController(IntPtr handle) : base (handle) {
		}
		
		public override void ViewDidLoad() {
			this.NavigationItem.Title = this.CategoryName;
			var source = new ProductTableViewSource();
			this.TableView.Source = source;
			source.LoadDataAsync(this.CategoryId, () => InvokeOnMainThread(() => this.TableView.ReloadData()));
		}
		
		public override void PrepareForSegue(UIStoryboardSegue segue, NSObject sender) {
			var dest = segue.DestinationViewController as ProductDetailViewController;
			var selectedRow = this.TableView.IndexPathForSelectedRow.Row;
			var source = this.TableView.Source as ProductTableViewSource;
			var p = source.Data[selectedRow];
			dest.ProductId = p.ProductID;
			dest.ProductName = p.ProductName;
		}
	}
}
