#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18046
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("Cn.Beginor.ContextActionMode.Resource", IsApplication=true)]

namespace Cn.Beginor.ContextActionMode
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Novell.MonoDroid.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060001
			public const int activity_main_action1 = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int activity_main_action2 = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int activity_main_context_action1 = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int activity_main_context_action2 = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int activity_main_context_action3 = 2131099653;
			
			// aapt resource value: 0x7f060000
			public const int activity_main_hello_textview = 2131099648;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int activity_main = 2130903040;
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f050000
			public const int activity_main = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int activity_main_context = 2131034113;
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040002
			public const int activity_main_action1 = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int activity_main_action2 = 2130968579;
			
			// aapt resource value: 0x7f040005
			public const int activity_main_context_action1 = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int activity_main_context_action2 = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int activity_main_context_action3 = 2130968583;
			
			// aapt resource value: 0x7f040004
			public const int activity_main_context_mode_title = 2130968580;
			
			// aapt resource value: 0x7f040001
			public const int activity_main_hello = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
