CFLAGS=-Wall -g

all: ex19

ex19: object.o

clean:
	rm -f ex14
	rm -f ex15
	rm -f ex16
	rm -f ex17
	rm -f ex18
	rm -f ex19
	rm -f object.o
	rm -f -R ex19.dSYM
	rm -f ex20
	rm -f -R ex20.dSYM