CFLAGS=-Wall -g

all: ex14 ex15 ex16 ex17 ex18 ex19 ex20 ex22_main ex23

ex19: object.o

ex22_main: ex22.o

clean:
	rm -f *.o
	rm -f -R *.dSYM
	rm -f ex14
	rm -f ex15
	rm -f ex16
	rm -f ex17
	rm -f ex18
	rm -f ex19
	rm -f ex20
	rm -f ex22_main
	rm -f ex23